version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_app:/app
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: ./streamlit_app
    container_name: streamlit_app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
